#! /bin/bash 
###########################################
# Sync Files to philly server.
# Add rc File -
# cd scripts
# echo "export DAGAMA_USERNAME=ubuntu" > dlp_rc
###########################################

# constants
baseDir=$(cd `dirname "$0"`;pwd)
. $baseDir/dlp_rc
remotePath="$DAGAMA_USERNAME@52.221.247.147:git/deeplearning"
localPath=network-model

# functions

# main 
[ -z "${BASH_SOURCE[0]}" -o "${BASH_SOURCE[0]}" = "$0" ] || return
cd $baseDir/..
rsync -av --exclude ".*" \
    --exclude "data/" \
    --exclude "logs/" \
    --exclude "runs/" \
    --exclude "*.pyc" \
    --exclude "__pycache__/" \
    $localPath $remotePath
